# Processing conference call data

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [33]:
from nltk.tokenize import sent_tokenize
import nltk
#nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
from nltk.stem import PorterStemmer
stemmer = SnowballStemmer("english")
stop = stopwords.words('english')
ps = PorterStemmer()
from nltk.tokenize import word_tokenize

In [34]:
#importing file
path = '/Users/jackphillips/Downloads/'
filename = 'output_csv_combine_2019.csv'

df = pd.read_csv(path+filename, header= None)

In [35]:
#taking a look at the data
df.head()

,0,1,2,3,4,5,6
0,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",OPERATOR,,,,(Operator Instructions) Our first question co...
1,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",DEANE MICHAEL DRAY,"RBC Capital Markets, Research Division - MD of...",ndustry & Electrical Equipment,0,"Maybe we could -- first of all, congratulatio..."
2,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",RONALD C. KEATING,Evoqua Water Technologies Corp.,"President, CEO & Director",1,"Yes. So Deane, we watch across many vertical ..."
3,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",NATHAN HARDIE JONES,"Stifel, Nicolaus & Company, Incorporated, Rese...",Analyst,0,I'd like to square a little bit some of the c...
4,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",BENEDICT J. STAS,Evoqua Water Technologies Corp.,"Executive VP, CFO & Treasurer",1,"Yes, Nathan, that's correct. When you look at..."

In [36]:
#renaming columns
df.columns=['conference','date','name','company','title','group','text']

In [38]:
df.head()

,conference,date,name,company,title,group,text
0,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",OPERATOR,,,,(Operator Instructions) Our first question co...
1,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",DEANE MICHAEL DRAY,"RBC Capital Markets, Research Division - MD of...",ndustry & Electrical Equipment,0,"Maybe we could -- first of all, congratulatio..."
2,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",RONALD C. KEATING,Evoqua Water Technologies Corp.,"President, CEO & Director",1,"Yes. So Deane, we watch across many vertical ..."
3,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",NATHAN HARDIE JONES,"Stifel, Nicolaus & Company, Incorporated, Rese...",Analyst,0,I'd like to square a little bit some of the c...
4,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",BENEDICT J. STAS,Evoqua Water Technologies Corp.,"Executive VP, CFO & Treasurer",1,"Yes, Nathan, that's correct. When you look at..."

In [15]:
#learning how to break paragraohs into sentences
text=df['text'][1]
token_text=sent_tokenize(text)
print(token_text)

[' Maybe we could -- first of all, congratulations on a strong rebound year and especially fourth quarter and cash flow.', 'So congrats to the team.', 'Maybe we can start with where and how the growth rate where you may be having some slowing that Ben mentioned.', 'There might be some slowing.', 'Where might you be seeing that?', "That's helpful.", 'And then just a quick question on the MEMCOR divestiture.', '5 years ago, it might have been considered very surprising to see an exit, but this is very much a stand-alone business, not a lot in the way of service around it.', 'So what were the factors in consideration that this was not a business that was core to Evoqua?']

In [39]:
#sentences tokenizer
df['tokenized']=[sent_tokenize(para) for para in df['text']]

In [40]:
df.head()

,conference,date,name,company,title,group,text,tokenized
0,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",OPERATOR,,,,(Operator Instructions) Our first question co...,[ (Operator Instructions) Our first question c...
1,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",DEANE MICHAEL DRAY,"RBC Capital Markets, Research Division - MD of...",ndustry & Electrical Equipment,0,"Maybe we could -- first of all, congratulatio...","[ Maybe we could -- first of all, congratulati..."
2,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",RONALD C. KEATING,Evoqua Water Technologies Corp.,"President, CEO & Director",1,"Yes. So Deane, we watch across many vertical ...","[ Yes., So Deane, we watch across many vertica..."
3,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",NATHAN HARDIE JONES,"Stifel, Nicolaus & Company, Incorporated, Rese...",Analyst,0,I'd like to square a little bit some of the c...,[ I'd like to square a little bit some of the ...
4,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",BENEDICT J. STAS,Evoqua Water Technologies Corp.,"Executive VP, CFO & Treasurer",1,"Yes, Nathan, that's correct. When you look at...","[ Yes, Nathan, that's correct., When you look ..."

In [317]:
#working for turning sentences into words
df['tokenized']=[word_tokenize(para) for para in df['sentenences']]

In [38]:
#dropping unneeded column
df.drop(['text'],axis=1)

,conference,date,name,company,title,group,tokenized
0,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",OPERATOR,,,,[ (Operator Instructions) Our first question c...
1,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",DEANE MICHAEL DRAY,"RBC Capital Markets, Research Division - MD of...",ndustry & Electrical Equipment,0,"[ Maybe we could -- first of all, congratulati..."
2,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",RONALD C. KEATING,Evoqua Water Technologies Corp.,"President, CEO & Director",1,"[ Yes., So Deane, we watch across many vertica..."
3,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",NATHAN HARDIE JONES,"Stifel, Nicolaus & Company, Incorporated, Rese...",Analyst,0,[ I'd like to square a little bit some of the ...
4,Q4 2019 Evoqua Water Technologies Corp Earning...,"November 21, 2019 Thursday",BENEDICT J. STAS,Evoqua Water Technologies Corp.,"Executive VP, CFO & Treasurer",1,"[ Yes, Nathan, that's correct., When you look ..."
...,...,...,...,...,...,...,...
246043,Q3 2019 Affiliated Managers Group Inc Earnings...,"October 28, 2019 Monday",THOMAS M. WOJCIK,"Affiliated Managers Group, Inc.",CFO,1,"[ Thanks, Craig., So maybe I'll just kind of r..."
246044,Q3 2019 Affiliated Managers Group Inc Earnings...,"October 28, 2019 Monday",ALEXANDER BLOSTEIN,"Goldman Sachs Group Inc., Research Division",Lead Capital Markets Analyst,0,[ Question for you guys around EBITDA yield on...
246045,Q3 2019 Affiliated Managers Group Inc Earnings...,"October 28, 2019 Monday",BENJAMIN JOSEPH HERBERT,"Citigroup Inc, Research Division",VP & Analyst,0,"[ It's Ben Herbert on for Bill., Just was hopi..."
246046,Q3 2019 Affiliated Managers Group Inc Earnings...,"October 28, 2019 Monday",DANIEL THOMAS FANNON,"Jefferies LLC, Research Division",Senior Equity Research Analyst,0,"[ Just on the reallocation of resources, Jay, ..."
246047,Q3 2019 Affiliated Managers Group Inc Earnings...,"October 28, 2019 Monday",MICHAEL ROGER CARRIER,"BofA Merrill Lynch, Research Division",Director,0,"[ Maybe just one more on M&A., Can you provide..."

In [45]:
# Create lists to fill with values
l_col1 = []
l_col2 = []
l_col3 = []

# iterate over each row and fill our lists
for ix, row in df.iterrows():
    for value in row['tokenized']:
        l_col1.append(value)
        l_col2.append(row['conference'])
        l_col3.append(row['group'])

# Create new dataframe from the two lists
df= pd.DataFrame({'sentenences': l_col1 ,
                         'conference': l_col2 , 'group': l_col3})
#df=df.rename(columns={"sentences":"sents"});

In [47]:
#saving new processed df
df.to_csv('/Users/jackphillips/Documents/bysentence.csv')

# Processing training data

In [100]:
#reading in data
new_df=pd.read_pickle('/Users/jackphillips/Downloads/wiki_sentences.pickle.txt')
new_df2=pd.read_pickle('/Users/jackphillips/Downloads/humorous_oneliners.pickle.txt')
reuters=pd.read_pickle('/Users/jackphillips/Downloads/reuters_headlines.pickle.txt')
proverbs=pd.read_pickle('/Users/jackphillips/Downloads/proverbs.pickle.txt')
double=pd.read_pickle('/Users/jackphillips/Downloads/oneliners_incl_doubles.pickle.txt')

In [108]:
#turning data in df
wiki=pd.DataFrame(new_df)
joke=pd.DataFrame(new_df2)
reuters=pd.DataFrame(reuters)
proverbs=pd.DataFrame(proverbs)
double=pd.DataFrame(double)

In [169]:
#renaming columns
reuters.columns=['text']
proverbs.columns=['text']
double.columns=['text']
wiki.columns=['text']
joke.columns=['text']

In [172]:
#creating humor label
reuters['humor']=False
proverbs['humor']=False
double['humor']=True
wiki['humor']=False
joke['humor']=True

In [182]:
#joining data
frames=[wiki,joke,reuters,proverbs,double]
data_all2=pd.concat(frames)

In [384]:
#joining data
frames=[wiki,joke2]
data_smalljoke=pd.concat(frames)

In [387]:
#creating csv files
data_smalljoke.to_csv('/Users/jackphillips/Documents/smalljoke.csv')
wiki.to_csv('/Users/jackphillips/Documents/wiki.csv')
data_all.to_csv('/Users/jackphillips/Documents/joke_wiki2.csv')

In [15]:
#preparing amazon data
az = pd.read_csv('/Users/jackphillips/Documents/Humorous.csv')
to_drop=['product_description','image_url','label']
az=az.drop(to_drop,axis=1)
az['humor']=True
az.to_csv('/Users/jackphillips/Documents/az.csv')